export const GO_SLIDE_BACK = 'GO_SLIDE_BACK';
export const GO_SLIDE_FORWARDS = 'GO_SLIDE_FORWARDS';
export const GO_ARTICLE_FORWARD = 'GO_ARTICLE_FORWARD';
export const GO_ARTICLE_BACK = 'GO_ARTICLE_BACK';

export const CLEAR_COUNTER = 'CLEAR_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const UPDATE_LABEL = 'UPDATE_LABEL';
