export const GO_SLIDE_BACK = 'GO_SLIDE_BACK';
export const GO_SLIDE_FORWARDS = 'GO_SLIDE_FORWARDS';
export const GO_ARTICLE_FORWARD = 'GO_ARTICLE_FORWARD';
export const GO_ARTICLE_BACK = 'GO_ARTICLE_BACK';
